import = ["~/.dotfiles/alacritty/catppuccin-mocha.toml"]
[window]
padding = { x = 5, y = 5}
opacity = 0.97
blur = true
[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Medium"}
bold = { family = "JetBrains Mono Nerd Font", style = "Bold"}
italic = { family = "JetBrains Mono Nerd Font", style = "Medium Italic"}
bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic"}
size = 11
[env]
TERM = "xterm-256color"
[keyboard]
bindings = [
{ key = "+", mode = "Vi", action = "Last"},
]

